ixl: fix warnings related to incorrect printf formats
When printing variables of size_t, the regular format specifiers such as
%lu are not accurate, because the size_t type may not be equivalent to a
long.

Fix this by using %zu which is used to represent size_t types to printf.

This resolves warnings similar to the following on 32-bit platforms:

  ixl_pf_main.c:5037:17: error: format specifies type 'unsigned long' but the argument has type 'size_t' (aka 'unsigned int') [-Werror,-Wformat]
                      __func__, ifd->ifd_len, sizeof(struct i40e_nvm_access));
                                ^~~~~~~~~~~~
  ixl_pf_main.c:5037:31: error: format specifies type 'unsigned long' but the argument has type 'unsigned int' [-Werror,-Wformat]
                      __func__, ifd->ifd_len, sizeof(struct i40e_nvm_access));
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Jacob Keller <jacob.e.keller@intel.com>